# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  Artifactory:
    type: npm-registry
    url: https://hpecds.jfrog.io/artifactory/api/npm/dscc-npm/
    token: ${{ secrets.CI_TOKEN_NPM_RO_DEPENDABOT_ARTIFACTORY }}
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    registries:
      - Artifactory
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
